---
version: "2"

services:
  node:
    build: ./docker/node/
    env_file:
      - .env
    environment:
      PORT: 8080
    expose:
      - "8080"
    volumes:
      - ".:/usr/src/app"
  nginx:
    restart: always
    build: ./docker/nginx/
    ports:
      - "${PORT}:80"
    volumes:
      - /www/public
    volumes_from:
      - node
    links:
      - node:node
